name: coastalmassageandwellnes.oi
favicon: null
layout_spectrum: 0.49886
typography_spectrum: 0.86187
title: Coastal Massage and Wellness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f35700'
    - '#3c3c37'
    - '#2eb5ad'
    - '#a9a9a7'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
