name: coastalmassageandwellnes.oi
favicon: null
layout_spectrum: 0.22051172074861825
typography_spectrum: 0.48315768083557487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6accd7'
    - '#e76617'
    - '#49423a'
    - '#8e8a85'
  brandStrength: 0.7399584699887782
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.0027493536472320557
purpose: []
